[build]
# this shouldn't have to exist but rust-analyzer doesn't properly handle target= if the config isn't in the same directory as the project
target = "x86_64-unknown-kernel.json"

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]